# -*- coding: utf-8 -*-
"""QR Code Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JuY5NjfNs9VLKqo559D7ofkl5bk1cr9K

Install **pyqrcode** module
"""

pip install pyqrcode

"""Install an additional module **pypng** to save image in png format"""

pip install pypng

"""To open Image, install **Pillow** module"""

pip install Pillow

"""# Code"""

import pyqrcode
import png
from PIL import Image

#inserting website name
s = input("Enter your website: ") 
print(s)
url = pyqrcode.create(s)

#saving image
img = "qr-code.png"
url.png(img, scale=10)

#opening image
im=Image.open(img)
im.show